// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDARhS1GztkDnz7-B2OvqmZNFfeM8hoSSE',
    appId: '1:116911756669:web:aa9e21a272ff4017e36814',
    messagingSenderId: '116911756669',
    projectId: 'ciscord-74ece',
    authDomain: 'ciscord-74ece.firebaseapp.com',
    storageBucket: 'ciscord-74ece.appspot.com',
    measurementId: 'G-MNLE4QCQ0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx6xltFyJU83pZvezlr2JdFGVJoPEVw1U',
    appId: '1:116911756669:android:6b4a5bf311cbb29be36814',
    messagingSenderId: '116911756669',
    projectId: 'ciscord-74ece',
    storageBucket: 'ciscord-74ece.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5wCffqkH808kamp9ykmrxrS238hgKvoo',
    appId: '1:116911756669:ios:b02204a1ef83b25ee36814',
    messagingSenderId: '116911756669',
    projectId: 'ciscord-74ece',
    storageBucket: 'ciscord-74ece.appspot.com',
    iosBundleId: 'com.example.ciscord',
  );
}
